### ISSUE TITLE
Git/Github

### ISSUE THREAD

**Issue by dimitarstoyanov95** [shain-app/backend#2]
Learn the basic concepts of what Git and Github are.

Objectives:

1 - Watch these videos:
[Git vs. GitHub: What's the difference?](https://www.youtube.com/watch?v=wpISo9TNjfU&t=1s)
[Git It? How to use Git and Github](https://www.youtube.com/watch?v=HkdAHXoRtos&t=6s)

Short tutorial:
[Git Tutorial For Dummies](https://www.youtube.com/watch?v=mJ-qvsxPHpY)

2 - Answer the questions bellow in the comment section.

**Comment by dimitarstoyanov95** [comment]
Answer these questions by modifying this file and adding your answer bellow the question.
Use ChatGPT

1. What is the difference between Git and Github

3. What are  the basic commands of git to create modify commit and push changes to a branch.

4. How does git stash work, and in what scenarios would it be useful?

5. Explain the difference between git fetch and git pull.

**Comment by Ha-ds** [comment]
1. Git tracks changes in a file, allows to record revisions, view history, branch, merge and revert code. It is installed on the local machine.
Github is used to store repositories online, collaborate on projects and manage pull requests. It is a web platform.
2. Initialize a Git repository: git init
    Initialize a Git repository: git clone
   Check the current status of the repository: git status
   Stage changes for commit: git add .
   Commit changes: git commit -m ""
   Push changes to a remote repository: git push origin branch-name
   Create a new branch: git checkout -b new-branch-name
  Switch to an existing branch: git checkout branch-name
3.git stash temporarily saves uncommitted changes without committing them, allowing switching branches or pulling changes without having conflicts.
Useful Scenario: when I'm working on sth but I need to switch to another branch to fix a bug
4. git fetch: Downloads updates from a remote repository, such as GitHub, but does not automatically merge them with your current branch.
   git pull: Combines both git fetch and git merge in one step. It downloads the changes from the remote repository and automatically merges them into your current branch.
